/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.iesalandalus.ejemploclase2.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.iesalandalus.ejemploclase2.controlador.LogicaNegocio;
import org.iesalandalus.ejemploclase2.modelo.Alumno;
import org.iesalandalus.ejemploclase2.modelo.modelosTabla.AlumnoTableModel;

/**
 *
 * @author jose
 */
public class JFrameVentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName());
    private LogicaNegocio ln;
    private AlumnoTableModel atm;
    
    /**
     * Creates new form JFrameVentanaPrincipal
     * @param ln
     */
    public JFrameVentanaPrincipal(LogicaNegocio ln) {
        initComponents();
        this.ln = ln;        
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFichero = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo 1");
        setLocationByPlatform(true);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(this::jButtonCerrarActionPerformed);

        jScrollPane1.setViewportView(jTableAlumnos);

        jMenuFichero.setText("Fichero");

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenuFichero.add(jMenuItemSalir);

        jMenuBar1.add(jMenuFichero);

        jMenuAlumnos.setText("Alumnos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Añadir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenuAlumnos.add(jMenuItem1);

        jMenuBar1.add(jMenuAlumnos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(jButtonCerrar)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogDatos jdd = new JDialogDatos(this,true);
        jdd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFichero;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumnos;
    // End of variables declaration//GEN-END:variables

    public void anadirAlumno(Alumno alumno) {
        ln.insertarAlumno(alumno);         
        actualizarTabla();
    }
    
    private void actualizarTabla(){   
        this.atm = new AlumnoTableModel(ln);
        this.jTableAlumnos.setModel(atm);
    }
}
